- name: show facts
  hosts: all
  tasks:
    - name: print facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: print os_family
      ansible.builtin.debug:
        var: ansible_facts["os_family"]  # var: ansible_facts.os_family 
       