- hosts: all
  tasks:
  - name: show IP address
    ansible.builtin.debug:
      msg: >
       This host uses IP address {{ ansible_facts.default_ipv4.address }}

      # Alternative:
      # This host uses IP address {{ ansible_facts['default_ipv4']['address'] }}
  - name: show distribution version
    ansible.builtin.debug:
      msg: This host uses {{ ansible_facts.distribution_version }} distribution version     
